language: node_js
node_js: 10
services:
  - docker
before_install:
- mkdir -p ~/schain_data/data_dir
- mv test/utils/config.json ~/schain_data/
- docker login --username $USERNAME --password $PASSWORD
- docker pull skalenetwork/schain:$SCHAIN_VERSION
- docker run -d
  -v ~/schain_data:/schain_data
  -p 2234:2234
  -e SSL_CERT_PATH=None
  -e HTTP_RPC_PORT=2234
  -e DATA_DIR=/schain_data/data_dir
  -e CONFIG_FILE=/schain_data/config.json
  skalenetwork/schain:$SCHAIN_VERSION
install:
- npm install

jobs:
  include:
    - stage: test
      script:
      - truffle compile
      - truffle test --network skaled
      after_success:
      - npx solidity-coverage
      - cat coverage/lcov.info | npx codecov
    - stage: integration
      install:
      - git clone https://github.com/skalenetwork/filestorage.js.git
      - cd filestorage.js
      - npm install
      - npm link; npm link @skalenetwork/filestorage.js
      before_script:
      - npm run generate
      script:
      - npm run test
